name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Setup pipenv
      uses: dschep/install-pipenv-action@v1
    - name: Install Dependencies
      run: |
        pipenv install
    - name: Run Tests
      run: |
        pipenv run python manage.py test


