name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Install the python interpreter
      run: |
        sudo apt-get install python${{ matrix.python-version }} python${{ matrix.python-version }}-dev libpq-dev
    - name: Install pipenv
      uses: dschep/install-pipenv-action@v1
    - name: Run Tests
      run: |
        pipenv --python ${{ matrix.python-version }} install
        pipenv run python -c "import sys; print(f'== Sanity check. Using python {sys.version}')"
        pipenv run python manage.py test
